// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "letto": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/rchampourlier/letto_go/design
// --out=$(GOPATH)/src/github.com/rchampourlier/letto_go
// --version=v1.2.0-dirty

package client

import (
	"github.com/goadesign/goa"
	"net/http"
)

// An automation workflow (default view)
//
// Identifier: application/letto.workflow+json; view=default
type LettoWorkflow struct {
	// Longer description of the workflow
	Description *string `form:"description,omitempty" json:"description,omitempty" xml:"description,omitempty"`
	// API href for reading a workflow
	Href string `form:"href" json:"href" xml:"href"`
	// Name for the workflow
	Name string `form:"name" json:"name" xml:"name"`
	// Workflow UUID
	UUID string `form:"uuid" json:"uuid" xml:"uuid"`
}

// Validate validates the LettoWorkflow media type instance.
func (mt *LettoWorkflow) Validate() (err error) {
	if mt.UUID == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "uuid"))
	}
	if mt.Href == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "href"))
	}
	if mt.Name == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "name"))
	}
	return
}

// An automation workflow (full view)
//
// Identifier: application/letto.workflow+json; view=full
type LettoWorkflowFull struct {
	// Longer description of the workflow
	Description *string `form:"description,omitempty" json:"description,omitempty" xml:"description,omitempty"`
	// API href for reading a workflow
	Href string `form:"href" json:"href" xml:"href"`
	// Name for the workflow
	Name string `form:"name" json:"name" xml:"name"`
	// Source code for the workflow
	Source string `form:"source" json:"source" xml:"source"`
	// Workflow UUID
	UUID string `form:"uuid" json:"uuid" xml:"uuid"`
}

// Validate validates the LettoWorkflowFull media type instance.
func (mt *LettoWorkflowFull) Validate() (err error) {
	if mt.UUID == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "uuid"))
	}
	if mt.Href == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "href"))
	}
	if mt.Name == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "name"))
	}
	if mt.Source == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "source"))
	}
	return
}

// An automation workflow (link view)
//
// Identifier: application/letto.workflow+json; view=link
type LettoWorkflowLink struct {
	// API href for reading a workflow
	Href string `form:"href" json:"href" xml:"href"`
}

// Validate validates the LettoWorkflowLink media type instance.
func (mt *LettoWorkflowLink) Validate() (err error) {
	if mt.Href == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "href"))
	}
	return
}

// DecodeLettoWorkflow decodes the LettoWorkflow instance encoded in resp body.
func (c *Client) DecodeLettoWorkflow(resp *http.Response) (*LettoWorkflow, error) {
	var decoded LettoWorkflow
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// DecodeLettoWorkflowFull decodes the LettoWorkflowFull instance encoded in resp body.
func (c *Client) DecodeLettoWorkflowFull(resp *http.Response) (*LettoWorkflowFull, error) {
	var decoded LettoWorkflowFull
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// DecodeLettoWorkflowLink decodes the LettoWorkflowLink instance encoded in resp body.
func (c *Client) DecodeLettoWorkflowLink(resp *http.Response) (*LettoWorkflowLink, error) {
	var decoded LettoWorkflowLink
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// LettoWorkflowlist media type (default view)
//
// Identifier: application/letto.workflowlist+json; view=default
type LettoWorkflowlist struct {
	// Links to related resources
	Links *LettoWorkflowlistLinks `form:"links,omitempty" json:"links,omitempty" xml:"links,omitempty"`
}

// LettoWorkflowlistLinks contains links to related resources of LettoWorkflowlist.
type LettoWorkflowlistLinks struct {
}

// DecodeLettoWorkflowlist decodes the LettoWorkflowlist instance encoded in resp body.
func (c *Client) DecodeLettoWorkflowlist(resp *http.Response) (*LettoWorkflowlist, error) {
	var decoded LettoWorkflowlist
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}
