// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "letto": Application User Types
//
// Command:
// $ goagen
// --design=github.com/rchampourlier/letto_backend/design
// --out=$(GOPATH)/src/github.com/rchampourlier/letto_backend
// --version=v1.3.0

package client
