// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "letto": Application User Types
//
// Command:
// $ goagen
// --design=github.com/rchampourlier/letto_go/design
// --out=$(GOPATH)/src/github.com/rchampourlier/letto_go
// --version=v1.2.0-dirty

package client
