// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "letto": workflow Resource Client
//
// Command:
// $ goagen
// --design=gitlab.com/letto/letto_backend/design
// --out=$(GOPATH)/src/gitlab.com/letto/letto_backend
// --version=v1.3.0

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// CreateWorkflowPayload is the workflow create action payload.
type CreateWorkflowPayload struct {
	// A way of grouping workflows together to be triggered by a specific endpoint's URL
	Group string `form:"group" json:"group" xml:"group"`
	// Name of the workflow
	Name string `form:"name" json:"name" xml:"name"`
	// Source code to execute for this workflow
	Source string `form:"source" json:"source" xml:"source"`
}

// CreateWorkflowPath computes a request path to the create action of workflow.
func CreateWorkflowPath() string {

	return fmt.Sprintf("/api/workflows")
}

// Create a new workflow
func (c *Client) CreateWorkflow(ctx context.Context, path string, payload *CreateWorkflowPayload) (*http.Response, error) {
	req, err := c.NewCreateWorkflowRequest(ctx, path, payload)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCreateWorkflowRequest create the request corresponding to the create action endpoint of the workflow resource.
func (c *Client) NewCreateWorkflowRequest(ctx context.Context, path string, payload *CreateWorkflowPayload) (*http.Request, error) {
	var body bytes.Buffer
	err := c.Encoder.Encode(payload, &body, "*/*")
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	header.Set("Content-Type", "application/json")
	return req, nil
}

// DeleteWorkflowPath computes a request path to the delete action of workflow.
func DeleteWorkflowPath(workflowUUID string) string {
	param0 := workflowUUID

	return fmt.Sprintf("/api/workflows/%s", param0)
}

// Delete a workflow by UUID
func (c *Client) DeleteWorkflow(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewDeleteWorkflowRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewDeleteWorkflowRequest create the request corresponding to the delete action endpoint of the workflow resource.
func (c *Client) NewDeleteWorkflowRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("DELETE", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// ListWorkflowPath computes a request path to the list action of workflow.
func ListWorkflowPath() string {

	return fmt.Sprintf("/api/workflows/")
}

// List workflows
func (c *Client) ListWorkflow(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewListWorkflowRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListWorkflowRequest create the request corresponding to the list action endpoint of the workflow resource.
func (c *Client) NewListWorkflowRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// ReadWorkflowPath computes a request path to the read action of workflow.
func ReadWorkflowPath(workflowUUID string) string {
	param0 := workflowUUID

	return fmt.Sprintf("/api/workflows/%s", param0)
}

// Read a workflow by UUID
func (c *Client) ReadWorkflow(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewReadWorkflowRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewReadWorkflowRequest create the request corresponding to the read action endpoint of the workflow resource.
func (c *Client) NewReadWorkflowRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// UpdateWorkflowPath computes a request path to the update action of workflow.
func UpdateWorkflowPath(workflowUUID string) string {
	param0 := workflowUUID

	return fmt.Sprintf("/api/workflows/%s", param0)
}

// Update an existing workflow by UUID
func (c *Client) UpdateWorkflow(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewUpdateWorkflowRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewUpdateWorkflowRequest create the request corresponding to the update action endpoint of the workflow resource.
func (c *Client) NewUpdateWorkflowRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("PUT", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
