version: '3'
services:
  web:
    build: .
    ports:
    - "9292:9292"
    volumes:
      - $HOME/letto_data:/tmp/data
      - $HOME/letto_logs:/tmp/logs
      - /var/run/docker.sock:/var/run/docker.sock
  execjs:
    build: ./exec/js
    volumes:
      - $HOME/letto_data:/usr/src/app/data
