basePath: /api
consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  CreateWorkflowPayload:
    example:
      group: Jordane Krajcik
      name: Eos sed quibusdam qui quia.
      source: Ut ex id qui.
    properties:
      group:
        description: A way of grouping workflows together to be triggered by a specific
          endpoint's URL
        example: Jordane Krajcik
        pattern: \A[\w-]+\z
        type: string
      name:
        description: Name of the workflow
        example: Eos sed quibusdam qui quia.
        type: string
      source:
        description: Source code to execute for this workflow
        example: Ut ex id qui.
        type: string
    required:
    - source
    - name
    - group
    title: CreateWorkflowPayload
    type: object
  LettoWorkflow:
    description: An automation workflow (default view)
    example:
      href: Repellat aut eos.
      name: Odio fuga alias.
      uuid: 66921ed1-5650-43fd-8d70-2b4a2ff4d783
    properties:
      href:
        description: API href for reading a workflow
        example: Repellat aut eos.
        type: string
      name:
        description: Name for the workflow
        example: Odio fuga alias.
        type: string
      uuid:
        description: Workflow UUID
        example: 66921ed1-5650-43fd-8d70-2b4a2ff4d783
        format: uuid
        type: string
    required:
    - uuid
    - href
    - name
    title: 'Mediatype identifier: application/letto.workflow+json; view=default'
    type: object
  LettoWorkflow_list:
    description: LettoWorkflow_list media type (default view)
    properties:
      links:
        $ref: '#/definitions/LettoWorkflow_listLinks'
    title: 'Mediatype identifier: application/letto.workflow_list+json; view=default'
    type: object
  LettoWorkflow_listLinks:
    description: LettoWorkflow_listLinks contains links to related resources of LettoWorkflow_list.
    title: LettoWorkflow_listLinks
    type: object
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
host: localhost:9292
info:
  description: Go service providing the backend API for Letto
  title: The place for your complex workflows
  version: ""
paths:
  /triggers/{group}:
    get:
      description: Receive incoming webhook
      operationId: triggers#webhook
      parameters:
      - in: path
        name: group
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: webhook triggers
      tags:
      - triggers
    post:
      description: Receive incoming webhook
      operationId: triggers#webhook#1
      parameters:
      - in: path
        name: group
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: webhook triggers
      tags:
      - triggers
  /workflows:
    post:
      description: Create a new workflow
      operationId: workflow#create
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/CreateWorkflowPayload'
      produces:
      - application/vnd.goa.error
      responses:
        "201":
          description: Resource created
          headers:
            Location:
              description: href to created resource
              pattern: \A/workflows/[^/]+/[\w-]+\z
              type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: create workflow
      tags:
      - workflow
  /workflows/:
    get:
      description: List workflows
      operationId: workflow#list
      produces:
      - application/letto.workflow_list+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/LettoWorkflow_list'
      schemes:
      - http
      summary: list workflow
      tags:
      - workflow
  /workflows/{workflowUUID}:
    delete:
      description: Delete a workflow by UUID
      operationId: workflow#delete
      parameters:
      - description: Workflow UUID
        in: path
        name: workflowUUID
        required: true
        type: string
      produces:
      - application/letto.workflow+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/LettoWorkflow'
      schemes:
      - http
      summary: delete workflow
      tags:
      - workflow
    get:
      description: Read a workflow by UUID
      operationId: workflow#read
      parameters:
      - description: Workflow UUID
        in: path
        name: workflowUUID
        required: true
        type: string
      produces:
      - application/letto.workflow+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/LettoWorkflow'
      schemes:
      - http
      summary: read workflow
      tags:
      - workflow
    put:
      description: Update an existing workflow by UUID
      operationId: workflow#update
      parameters:
      - description: Workflow UUID
        in: path
        name: workflowUUID
        required: true
        type: string
      produces:
      - application/letto.workflow+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/LettoWorkflow'
      schemes:
      - http
      summary: update workflow
      tags:
      - workflow
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  OK:
    description: OK
schemes:
- http
swagger: "2.0"
