consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  LettoWorkflow:
    description: An automation workflow (default view)
    example:
      description: Repellat aut eos.
      href: Odio fuga alias.
      name: Distinctio consectetur sequi atque.
      uuid: Qui quia.
    properties:
      description:
        description: Longer description of the workflow
        example: Repellat aut eos.
        type: string
      href:
        description: API href for reading a workflow
        example: Odio fuga alias.
        type: string
      name:
        description: Name for the workflow
        example: Distinctio consectetur sequi atque.
        type: string
      uuid:
        description: Workflow UUID
        example: Qui quia.
        type: string
    required:
    - uuid
    - href
    - name
    title: 'Mediatype identifier: application/letto.workflow+json; view=default'
    type: object
  LettoWorkflowlist:
    description: LettoWorkflowlist media type (default view)
    properties:
      links:
        $ref: '#/definitions/LettoWorkflowlistLinks'
    title: 'Mediatype identifier: application/letto.workflowlist+json; view=default'
    type: object
  LettoWorkflowlistLinks:
    description: LettoWorkflowlistLinks contains links to related resources of LettoWorkflowlist.
    title: LettoWorkflowlistLinks
    type: object
host: localhost:9292
info:
  description: Go/Goa service providing the backend API for Letto
  title: The place for your complex workflows
  version: ""
paths:
  /workflows/:
    get:
      description: List workflows
      operationId: workflow#list
      produces:
      - application/letto.workflowlist+json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/LettoWorkflowlist'
        "404":
          description: Content not found
      schemes:
      - http
      summary: list workflow
      tags:
      - workflow
    post:
      description: Create a new workflow
      operationId: workflow#create
      produces:
      - application/letto.workflow+json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/LettoWorkflow'
        "404":
          description: Content not found
      schemes:
      - http
      summary: create workflow
      tags:
      - workflow
  /workflows/{workflowUUID}:
    delete:
      description: Delete a workflow by UUID
      operationId: workflow#delete
      parameters:
      - description: Workflow UUID
        in: path
        name: workflowUUID
        required: true
        type: string
      produces:
      - application/letto.workflow+json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/LettoWorkflow'
        "404":
          description: Content not found
      schemes:
      - http
      summary: delete workflow
      tags:
      - workflow
    get:
      description: Read a workflow by UUID
      operationId: workflow#read
      parameters:
      - description: Workflow UUID
        in: path
        name: workflowUUID
        required: true
        type: string
      produces:
      - application/letto.workflow+json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/LettoWorkflow'
        "404":
          description: Content not found
      schemes:
      - http
      summary: read workflow
      tags:
      - workflow
    put:
      description: Update an existing workflow by UUID
      operationId: workflow#update
      parameters:
      - description: Workflow UUID
        in: path
        name: workflowUUID
        required: true
        type: string
      produces:
      - application/letto.workflow+json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/LettoWorkflow'
        "404":
          description: Content not found
      schemes:
      - http
      summary: update workflow
      tags:
      - workflow
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
schemes:
- http
swagger: "2.0"
