// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "letto": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/rchampourlier/letto_go/design
// --out=$(GOPATH)/src/github.com/rchampourlier/letto_go
// --version=v1.3.0

package app
