// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "letto": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=gitlab.com/letto/letto_backend/design
// --out=$(GOPATH)/src/gitlab.com/letto/letto_backend
// --version=v1.3.0

package app

import (
	"fmt"
)

// WorkflowHref returns the workflow href.
func WorkflowHref(path string) string {
	return fmt.Sprintf("/api/workflows/%s", path)
}
